### ISSUE TITLE
It does not work in headless mode.

### ISSUE THREAD

**Issue by sinzy0925** [mihi314/puppeteer-trigger-chrome-zoom#1]
When I run it in headless mode, I get an error
const targets = await browser.targets();
is missing the contents of targets.

Also
const extenstionPageTarget = targets.find(
        (target) => target._targetInfo.title === extensionName
);
the result of extenstionPageTarget will be undefined.

Can you please tell me how to make it work in headless mode?
Please let me know.

**Comment by mihi314** [comment]
This repository relies on an extension to work. Unfortunately chrome does not support extensions in headless mode, which causes the error. See [here](https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c5) for details. 

Maybe the `--force-device-scale-factor` option (which does seem to work in headless mode) or another method mentioned in [the stackoverflow question](https://stackoverflow.com/questions/57802309/is-there-a-way-to-trigger-standard-zoom-not-headless) works for you?
